### PR TITLE
Add missing <utility> include

### PR DESCRIPTION
**Pull request by peckato1**
After upgrading g++ package to 12.1.0 on archlinux I see the following
compilation error:

  /usr/include/argparse/argparse.hpp: In member function ‘void argparse::ArgumentParser::index_argument(list_iterator)’:
  /usr/include/argparse/argparse.hpp:1167:34: error: ‘as_const’ is not a member of ‘std’; did you mean ‘is_const’?
   1167 |     for (const auto &name : std::as_const(it->m_names)) {
        |                                  ^~~~~~~~
        |                                  is_const

It turns out that std::as_const comes from <utility> header [1] which
was not explicitly included.

[1] https://en.cppreference.com/w/cpp/utility/as_const

### CODE REVIEW

**Comment by skrobinson** [comment]
Thank you for sharing. This does seem a consequence of [changes in GCC 12](https://gcc.gnu.org/gcc-12/porting_to.html#header-dep-changes).

**Review by skrobinson — APPROVED** [review]

**Review by bebuch — APPROVED** [review]
